extends:
  - airbnb-base
  - plugin:prettier/recommended
  - plugin:jest/recommended

plugins:
  - prettier

env:
  node: true

rules:
  no-console: 0
  import/extensions: 0
  prettier/prettier: error
